In [19]:
import pandas as pd
from sklearn import linear_model
import numpy as np
import matplotlib.pyplot as plt

dtype_dict = {'bathrooms':float, 'waterfront':int, 'sqft_above':int, 'sqft_living15':float, 'grade':int, 'yr_renovated':int, 'price':float, 'bedrooms':float, 'zipcode':str, 'long':float, 'sqft_lot15':float, 'sqft_living':float, 'floors':float, 'condition':int, 'lat':float, 'date':str, 'sqft_basement':int, 'yr_built':int, 'id':str, 'sqft_lot':int, 'view':int}

sales = pd.read_csv('kc_house_data.csv', dtype=dtype_dict)
sales = sales.sort_values(['sqft_living','price'])
sales

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
19452,3980300371,20140926T000000,142000.0,0.0,0.00,290.0,20875,1.0,0,0,...,1,290,0,1963,0,98024,47.5308,-121.888,1620.0,22850.0
15381,2856101479,20140701T000000,276000.0,1.0,0.75,370.0,1801,1.0,0,0,...,5,370,0,1923,0,98117,47.6778,-122.389,1340.0,5000.0
860,1723049033,20140620T000000,245000.0,1.0,0.75,380.0,15000,1.0,0,0,...,5,380,0,1963,0,98168,47.4810,-122.323,1170.0,15000.0
18379,1222029077,20141029T000000,265000.0,0.0,0.75,384.0,213444,1.0,0,0,...,4,384,0,2003,0,98070,47.4177,-122.491,1920.0,224341.0
4868,6896300380,20141002T000000,228000.0,0.0,1.00,390.0,5900,1.0,0,0,...,4,390,0,1953,0,98118,47.5260,-122.261,2170.0,6000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8092,1924059029,20140617T000000,4668000.0,5.0,6.75,9640.0,13068,1.0,1,4,...,12,4820,4820,1983,2009,98040,47.5570,-122.210,3270.0,10454.0
9254,9208900037,20140919T000000,6885000.0,6.0,7.75,9890.0,31374,2.0,0,4,...,13,8860,1030,2001,0,98039,47.6305,-122.240,4540.0,42730.0
3914,9808700762,20140611T000000,7062500.0,5.0,4.50,10040.0,37325,2.0,1,2,...,11,7680,2360,1940,2001,98004,47.6500,-122.214,3930.0,25449.0
7252,6762700020,20141013T000000,7700000.0,6.0,8.00,12050.0,27600,2.5,0,3,...,13,8570,3480,1910,1987,98102,47.6298,-122.323,3940.0,8800.0
12777,1225069038,20140505T000000,2280000.0,7.0,8.00,13540.0,307752,3.0,0,4,...,12,9410,4130,1999,0,98053,47.6675,-121.986,4850.0,217800.0

In [20]:
def polynomial_sframe(feature, degree):
    # assume that degree >= 1
    # initialize the SFrame:
    poly_frame = pd.DataFrame()
    # and set poly_sframe['power_1'] equal to the passed feature
    poly_frame['power_1']=feature
    # first check if degree > 1
    if degree > 1:
        # then loop over the remaining degrees
        # range usually starts at 0 and stops at the endpoint-1. We want it to start at 2 and stop at degree
        for power in range(2, degree+1): 
            # first we'll give the column a name:
            name = 'power_' + str(power)
            # then assign poly_sframe[name] to the appropriate power of feature
            poly_frame[name]=np.power(feature,power)
#             print(power,(feature)**power)

    return poly_frame

In [40]:
l2_small_penalty = 1.5e-5
print("{0:.11f}".format(l2_small_penalty))
poly15_data = polynomial_sframe(sales['sqft_living'], 15) # use equivalent of `polynomial_sframe`
model = linear_model.Ridge(alpha=l2_small_penalty, normalize=True)
model.fit(poly15_data, sales['price'])
print(model.coef_)

0.00001500000
[ 1.24873306e+02 -4.77376011e-02  3.01446238e-05 -2.44419942e-09
 -1.94153675e-13  8.54085686e-18  1.51142121e-21  8.27979094e-26
  6.52603100e-31 -3.27895017e-34 -3.87962315e-38 -2.72437650e-42
 -1.07790800e-46  3.78242694e-51  1.39790296e-54]

In [22]:
set_1 = pd.read_csv('wk3_kc_house_set_1_data.csv', dtype=dtype_dict)
set_2 = pd.read_csv('wk3_kc_house_set_2_data.csv', dtype=dtype_dict)
set_3 = pd.read_csv('wk3_kc_house_set_3_data.csv', dtype=dtype_dict)
set_4 = pd.read_csv('wk3_kc_house_set_4_data.csv', dtype=dtype_dict)

In [23]:
l2_small_penalty=1e-9
# print(float(l2_small_penalty))
print("{0:.11f}".format(l2_small_penalty))

0.00000000100

In [59]:
poly15_data1 = polynomial_sframe(set_1['sqft_living'], 15) # use equivalent of `polynomial_sframe`
model = linear_model.Ridge(alpha=l2_small_penalty, normalize=True)
model.fit(poly15_data1, set_1['price'])
l=map(lambda i:"{0:.20f}".format(i),list(model.coef_))
print(list(l))
poly15_data2 = polynomial_sframe(set_2['sqft_living'], 15) 
model = linear_model.Ridge(alpha=l2_small_penalty, normalize=True)
model.fit(poly15_data2, set_2['price'])
l=map(lambda i:"{0:.20f}".format(i),list(model.coef_))
print(list(l))
poly15_data3 = polynomial_sframe(set_3['sqft_living'], 15) 
model = linear_model.Ridge(alpha=l2_small_penalty, normalize=True)
model.fit(poly15_data3, set_3['price'])
l=map(lambda i:"{0:.20f}".format(i),list(model.coef_))
print(list(l))
poly15_data4= polynomial_sframe(set_4['sqft_living'], 15) 
model = linear_model.Ridge(alpha=l2_small_penalty, normalize=True)
model.fit(poly15_data4, set_4['price'])
l=map(lambda i:"{0:.20f}".format(i),list(model.coef_))
print(list(l))

['-15.21071783062537896569', '0.04322619438532191577', '0.00000761301379227169', '-0.00000000101052500813', '-0.00000000000003598302', '0.00000000000000000280', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '-0.00000000000000000000', '-0.00000000000000000000', '-0.00000000000000000000', '-0.00000000000000000000', '-0.00000000000000000000', '0.00000000000000000000']
['288.18511529962120221171', '-0.10066666994219287956', '0.00001969373952387326', '0.00000000273446796367', '-0.00000000000021512695', '-0.00000000000000005519', '-0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '-0.00000000000000000000', '-0.00000000000000000000', '-0.00000000000000000000']
['187.17453637213000661177', '-0.06120769506468334148', '0.00002365132598753709', '-0.00000000019860925826', '-0.00000000000025207285', '-0.00000000000000001184', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '-0.00000000000000000000', '-0.00000000000000000000', '-0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000']
['129.00515479705902066598', '0.02495608553328127616', '-0.00001328202123651148', '0.00000000200483867588', '0.00000000000069094111', '0.00000000000000001952', '-0.00000000000000000001', '-0.00000000000000000000', '-0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '-0.00000000000000000000']

In [37]:
# plt.plot(poly15_data1['power_1'],model.predict(set_1['sqft_living'].values[:, np.newaxis]),'.')
#          poly15_data['power_1'], model2.predict(set_2['sqft_living']),'-',
#         poly15_data1['power_1'],model.predict(set_1['sqft_living']),'x',
#          poly15_data1['power_1'],model.predict(set_1['sqft_living']),'o',
#          )
poly15_data

,power_1,power_2,power_3,power_4,power_5,power_6,power_7,power_8,power_9,power_10,power_11,power_12,power_13,power_14,power_15
19452,290.0,84100.0,2.438900e+07,7.072810e+09,2.051115e+12,5.948233e+14,1.724988e+17,5.002464e+19,1.450715e+22,4.207072e+24,1.220051e+27,3.538148e+29,1.026063e+32,2.975582e+34,8.629189e+36
15381,370.0,136900.0,5.065300e+07,1.874161e+10,6.934396e+12,2.565726e+15,9.493188e+17,3.512479e+20,1.299617e+23,4.808584e+25,1.779176e+28,6.582952e+30,2.435692e+33,9.012061e+35,3.334463e+38
860,380.0,144400.0,5.487200e+07,2.085136e+10,7.923517e+12,3.010936e+15,1.144156e+18,4.347792e+20,1.652161e+23,6.278212e+25,2.385721e+28,9.065738e+30,3.444980e+33,1.309093e+36,4.974552e+38
18379,384.0,147456.0,5.662310e+07,2.174327e+10,8.349416e+12,3.206176e+15,1.231172e+18,4.727699e+20,1.815436e+23,6.971275e+25,2.676970e+28,1.027956e+31,3.947353e+33,1.515783e+36,5.820608e+38
4868,390.0,152100.0,5.931900e+07,2.313441e+10,9.022420e+12,3.518744e+15,1.372310e+18,5.352009e+20,2.087284e+23,8.140406e+25,3.174758e+28,1.238156e+31,4.828807e+33,1.883235e+36,7.344616e+38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8092,9640.0,92929600.0,8.958413e+11,8.635911e+15,8.325018e+19,8.025317e+23,7.736406e+27,7.457895e+31,7.189411e+35,6.930592e+39,6.681091e+43,6.440572e+47,6.208711e+51,5.985197e+55,5.769730e+59
9254,9890.0,97812100.0,9.673617e+11,9.567207e+15,9.461968e+19,9.357886e+23,9.254949e+27,9.153145e+31,9.052460e+35,8.952883e+39,8.854401e+43,8.757003e+47,8.660676e+51,8.565409e+55,8.471189e+59
3914,10040.0,100801600.0,1.012048e+12,1.016096e+16,1.020161e+20,1.024241e+24,1.028338e+28,1.032452e+32,1.036581e+36,1.040728e+40,1.044891e+44,1.049070e+48,1.053266e+52,1.057480e+56,1.061709e+60
7252,12050.0,145202500.0,1.749690e+12,2.108377e+16,2.540594e+20,3.061416e+24,3.689006e+28,4.445252e+32,5.356529e+36,6.454617e+40,7.777813e+44,9.372265e+48,1.129358e+53,1.360876e+57,1.639856e+61
12777,13540.0,183331600.0,2.482310e+12,3.361048e+16,4.550858e+20,6.161862e+24,8.343162e+28,1.129664e+33,1.529565e+37,2.071031e+41,2.804176e+45,3.796855e+49,5.140941e+53,6.960834e+57,9.424970e+61

In [38]:
set_1

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,8658300340,20140523T000000,80000.0,1.0,0.75,430.0,5050,1.0,0,0,...,4,430,0,1912,0,98014,47.6499,-121.909,1200.0,7500.0
1,1352300580,20141114T000000,247000.0,1.0,1.00,460.0,4120,1.0,0,0,...,4,460,0,1937,0,98055,47.4868,-122.199,990.0,4120.0
2,1320069249,20141020T000000,192500.0,1.0,1.00,470.0,63737,1.0,0,2,...,5,470,0,1924,0,98022,47.2163,-121.984,1350.0,46762.0
3,1437500015,20140709T000000,150000.0,3.0,0.75,490.0,38500,1.5,0,0,...,5,490,0,1959,0,98014,47.7112,-121.315,800.0,18297.0
4,0859000110,20141002T000000,125000.0,1.0,1.00,500.0,7440,1.0,0,0,...,5,500,0,1928,0,98106,47.5252,-122.362,1350.0,7440.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5399,8907500070,20150413T000000,5350000.0,5.0,5.00,8000.0,23985,2.0,0,4,...,12,6720,1280,2009,0,98004,47.6232,-122.220,4600.0,21750.0
5400,1247600105,20141020T000000,5110800.0,5.0,5.25,8010.0,45517,2.0,1,4,...,12,5990,2020,1999,0,98033,47.6767,-122.211,3430.0,26788.0
5401,2303900035,20140611T000000,2888000.0,5.0,6.25,8670.0,64033,2.0,0,4,...,13,6120,2550,1965,2003,98177,47.7295,-122.372,4140.0,81021.0
5402,6762700020,20141013T000000,7700000.0,6.0,8.00,12050.0,27600,2.5,0,3,...,13,8570,3480,1910,1987,98102,47.6298,-122.323,3940.0,8800.0
5403,1225069038,20140505T000000,2280000.0,7.0,8.00,13540.0,307752,3.0,0,4,...,12,9410,4130,1999,0,98053,47.6675,-121.986,4850.0,217800.0

In [61]:
l2_large_penalty=1.23e2
# print(float(l2_small_penalty))
print("{0:.11f}".format(l2_large_penalty))

poly15_data1 = polynomial_sframe(set_1['sqft_living'], 15) # use equivalent of `polynomial_sframe`
model = linear_model.Ridge(alpha=l2_large_penalty, normalize=True)
model.fit(poly15_data1, set_1['price'])
l=map(lambda i:"{0:.20f}".format(i),list(model.coef_))
print(list(l))
poly15_data2 = polynomial_sframe(set_2['sqft_living'], 15) 
model = linear_model.Ridge(alpha=l2_large_penalty, normalize=True)
model.fit(poly15_data2, set_2['price'])
l=map(lambda i:"{0:.20f}".format(i),list(model.coef_))
print(list(l))
poly15_data3 = polynomial_sframe(set_3['sqft_living'], 15) 
model = linear_model.Ridge(alpha=l2_large_penalty, normalize=True)
model.fit(poly15_data3, set_3['price'])
l=map(lambda i:"{0:.20f}".format(i),list(model.coef_))
print(list(l))
poly15_data4= polynomial_sframe(set_4['sqft_living'], 15) 
model = linear_model.Ridge(alpha=l2_large_penalty, normalize=True)
model.fit(poly15_data4, set_4['price'])
l=map(lambda i:"{0:.20f}".format(i),list(model.coef_))
print(list(l))

123.00000000000
['2.32806802957932479359', '0.00035362160794180360', '0.00000003319696917703', '0.00000000000200082477', '0.00000000000000011149', '0.00000000000000000001', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000']
['2.09756902777855502862', '0.00039081748325338903', '0.00000006671899443540', '0.00000000000890002997', '0.00000000000000097264', '0.00000000000000000010', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000']
['2.28906258118920513667', '0.00041247218983297203', '0.00000006088353446957', '0.00000000000658572163', '0.00000000000000061528', '0.00000000000000000006', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000']
['2.08596194091930708936', '0.00040503577180177130', '0.00000007468646473012', '0.00000000001130966078', '0.00000000000000145864', '0.00000000000000000017', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000', '0.00000000000000000000']

In [62]:
train_valid_shuffled = pd.read_csv('wk3_kc_house_train_valid_shuffled.csv', dtype=dtype_dict)
test = pd.read_csv('wk3_kc_house_test_data.csv', dtype=dtype_dict)

In [108]:
def get_rss(predictions,output):
    RSS=predictions-output
    RSS=RSS*RSS
    RSS=RSS.sum()
    return RSS

n = len(train_valid_shuffled)
k = 10 # 10-fold cross-validation


for i in range(k):
    start = (n*i)//k
    end = (n*(i+1))//k-1
    print(i, (start, end))
    val_set=train_valid_shuffled[start:end+1]
    train_set=train_valid_shuffled[0:start].append(train_valid_shuffled[end+1:n])
#     poly15_data= polynomial_sframe(train_set['sqft_living'], 15) 
    model = linear_model.Ridge(alpha=l2_penalty, normalize=True)
    model.fit(train_set, train_set['price'])
#     poly15_data_val= polynomial_sframe(val_set['sqft_living'], 15) 
#     poly15_data_val['price'] = val_set['price']
    predictions=model.predict(val_set.iloc[:,:15].values)
    error=get_rss(predictions,poly15_data_val["price"])

0 (0, 1938)

ValueError: could not convert string to float: '20150313T000000'

In [92]:
def k_fold_cross_validation(k_fold_cross_validation, l2_penalty, data):
    error=0
    for i in range(k):
        start = (n*i)//k
        end = (n*(i+1))//k-1
#         print(i, (start, end))
        val_set=data[start:end+1]
        train_set=data[0:start].append(data[end+1:n])
        poly15_data= polynomial_sframe(train_set['sqft_living'], 15) 
        model = linear_model.Ridge(alpha=l2_penalty, normalize=True)
        model.fit(poly15_data, train_set['price'])
        poly15_data_val= polynomial_sframe(val_set['sqft_living'], 15) 
        poly15_data_val['price'] = val_set['price']
        predictions=model.predict(poly15_data_val.loc[:,:'power_15'].values)
        error+=get_rss(predictions,poly15_data_val["price"])
    return error/k 

l2_penalty=np.logspace(3, 9, num=13)
l=[]
for i in l2_penalty:
#     print(i)
    l.append(k_fold_cross_validation(10,i,train_valid_shuffled))
#     print("\n")
print(l)
print(min(l))

1000.0
3162.2776601683795
10000.0
31622.776601683792
100000.0
316227.7660168379
1000000.0
3162277.6601683795
10000000.0
31622776.60168379
100000000.0
316227766.01683795
1000000000.0
[264977361036975.94, 265692935858318.25, 265924368957215.66, 265998081509342.66, 266021444553980.5, 266028837918724.5, 266031176438467.9, 266031915996607.4, 266032149870752.5, 266032223828783.66, 266032247216419.84, 266032254612245.16, 266032256951011.06]
264977361036975.94

In [76]:
poly15_data

,power_1,power_2,power_3,power_4,power_5,power_6,power_7,power_8,power_9,power_10,power_11,power_12,power_13,power_14,power_15,price
0,2800.0,7840000.0,2.195200e+10,6.146560e+13,1.721037e+17,4.818903e+20,1.349293e+24,3.778020e+27,1.057846e+31,2.961968e+34,8.293509e+37,2.322183e+41,6.502111e+44,1.820591e+48,5.097655e+51,665000.0
1,2490.0,6200100.0,1.543825e+10,3.844124e+13,9.571869e+16,2.383395e+20,5.934654e+23,1.477729e+27,3.679545e+30,9.162067e+33,2.281355e+37,5.680573e+40,1.414463e+44,3.522012e+47,8.769810e+50,645000.0
2,2340.0,5475600.0,1.281290e+10,2.998220e+13,7.015834e+16,1.641705e+20,3.841590e+23,8.989320e+26,2.103501e+30,4.922192e+33,1.151793e+37,2.695196e+40,6.306758e+43,1.475781e+47,3.453328e+50,640000.0
3,1320.0,1742400.0,2.299968e+09,3.035958e+12,4.007464e+15,5.289853e+18,6.982606e+21,9.217040e+24,1.216649e+28,1.605977e+31,2.119890e+34,2.798254e+37,3.693696e+40,4.875678e+43,6.435895e+46,594000.0
4,1904.0,3625216.0,6.902411e+09,1.314219e+13,2.502273e+16,4.764328e+19,9.071281e+22,1.727172e+26,3.288535e+29,6.261371e+32,1.192165e+36,2.269882e+39,4.321856e+42,8.228813e+45,1.566766e+49,365000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19391,2480.0,6150400.0,1.525299e+10,3.782742e+13,9.381200e+16,2.326538e+20,5.769813e+23,1.430914e+27,3.548666e+30,8.800692e+33,2.182572e+37,5.412777e+40,1.342369e+44,3.329075e+47,8.256105e+50,325000.0
19392,1670.0,2788900.0,4.657463e+09,7.777963e+12,1.298920e+16,2.169196e+19,3.622558e+22,6.049671e+25,1.010295e+29,1.687193e+32,2.817612e+35,4.705412e+38,7.858038e+41,1.312292e+45,2.191528e+48,545000.0
19393,2403.0,5774409.0,1.387590e+10,3.334380e+13,8.012515e+16,1.925407e+20,4.626754e+23,1.111809e+27,2.671677e+30,6.420040e+33,1.542736e+37,3.707193e+40,8.908386e+43,2.140685e+47,5.144066e+50,519900.0
19394,3780.0,14288400.0,5.401015e+10,2.041584e+14,7.717187e+17,2.917097e+21,1.102662e+25,4.168064e+28,1.575528e+32,5.955497e+35,2.251178e+39,8.509452e+42,3.216573e+46,1.215865e+50,4.595968e+53,1153000.0
19395,2400.0,5760000.0,1.382400e+10,3.317760e+13,7.962624e+16,1.911030e+20,4.586471e+23,1.100753e+27,2.641808e+30,6.340338e+33,1.521681e+37,3.652035e+40,8.764883e+43,2.103572e+47,5.048573e+50,338000.0

In [82]:
np.logspace(3, 9, num=13)

array([1.00000000e+03, 3.16227766e+03, 1.00000000e+04, 3.16227766e+04,
       1.00000000e+05, 3.16227766e+05, 1.00000000e+06, 3.16227766e+06,
       1.00000000e+07, 3.16227766e+07, 1.00000000e+08, 3.16227766e+08,
       1.00000000e+09])

In [93]:
train=pd.read_csv("wk3_kc_house_train_data.csv")
test=pd.read_csv("wk3_kc_house_test_data.csv")

In [104]:
l2_penalty=1000
poly15_data= polynomial_sframe(train['sqft_living'], 15) 
model = linear_model.Ridge(alpha=l2_penalty, normalize=True)
model.fit(poly15_data, train['price'])
poly15_data_test= polynomial_sframe(test['sqft_living'], 15) 
poly15_data_test['price'] = test['price']
predictions=model.predict(poly15_data_test.iloc[:,:15].values)
error=get_rss(predictions,poly15_data_test["price"])

In [105]:
print(error)

283706518061282.5

In [101]:
poly15_data_test.loc[:,:'power_15'].values.shape

(2217, 15)

In [103]:
poly15_data_test.iloc[:,:15].values.shape

(2217, 15)

In [106]:
print("{0:.20f}".format(8e13))

80000000000000.00000000000000000000

In [124]:
from decimal import Decimal

'%.2E' % Decimal('283706518061282.5')

'2.84E+14'

In [122]:
def k_fold_cross_validation(k, l2_penalty, data):
    error=0
    for i in range(k):
        start = (n*i)//k
        end = (n*(i+1))//k-1
#         print(i, (start, end))
        val_set=data[start:end+1]
        train_set=data[0:start].append(data[end+1:n])
#         poly15_data= polynomial_sframe(train_set['sqft_living'], 15) 
        model = linear_model.Ridge(alpha=l2_penalty, normalize=True)
        model.fit(train_set.iloc[:,:15].values, train_set['price'])
#         poly15_data_val= polynomial_sframe(val_set['sqft_living'], 15) 
#         poly15_data_val['price'] = val_set['price']
        predictions=model.predict(val_set.iloc[:,:15].values)
        error+=get_rss(predictions,val_set["price"])
    return error/k 

l2_penalty=np.logspace(3, 9, num=13)
l=[]
for i in l2_penalty:
    print(i)
    poly_data = polynomial_sframe(train_valid_shuffled['sqft_living'], 15)
    poly_data["price"]=train_valid_shuffled["price"]
    l.append(k_fold_cross_validation(10,i,poly_data))
    print("\n")
print(l)
print(min(l))

1000.0


3162.2776601683795


10000.0


31622.776601683792


100000.0


316227.7660168379


1000000.0


3162277.6601683795


10000000.0


31622776.60168379


100000000.0


316227766.01683795


1000000000.0


[264977361036975.94, 265692935858318.25, 265924368957215.66, 265998081509342.66, 266021444553980.5, 266028837918724.5, 266031176438467.9, 266031915996607.4, 266032149870752.5, 266032223828783.66, 266032247216419.84, 266032254612245.16, 266032256951011.06]
264977361036975.94

In [121]:
poly_data = polynomial_sframe(train_valid_shuffled['sqft_living'], 15)
poly_data["price"]=train_valid_shuffled["price"]
poly_data.iloc[:,:16]

,power_1,power_2,power_3,power_4,power_5,power_6,power_7,power_8,power_9,power_10,power_11,power_12,power_13,power_14,power_15,price
0,2800.0,7840000.0,2.195200e+10,6.146560e+13,1.721037e+17,4.818903e+20,1.349293e+24,3.778020e+27,1.057846e+31,2.961968e+34,8.293509e+37,2.322183e+41,6.502111e+44,1.820591e+48,5.097655e+51,665000.0
1,2490.0,6200100.0,1.543825e+10,3.844124e+13,9.571869e+16,2.383395e+20,5.934654e+23,1.477729e+27,3.679545e+30,9.162067e+33,2.281355e+37,5.680573e+40,1.414463e+44,3.522012e+47,8.769810e+50,645000.0
2,2340.0,5475600.0,1.281290e+10,2.998220e+13,7.015834e+16,1.641705e+20,3.841590e+23,8.989320e+26,2.103501e+30,4.922192e+33,1.151793e+37,2.695196e+40,6.306758e+43,1.475781e+47,3.453328e+50,640000.0
3,1320.0,1742400.0,2.299968e+09,3.035958e+12,4.007464e+15,5.289853e+18,6.982606e+21,9.217040e+24,1.216649e+28,1.605977e+31,2.119890e+34,2.798254e+37,3.693696e+40,4.875678e+43,6.435895e+46,594000.0
4,1904.0,3625216.0,6.902411e+09,1.314219e+13,2.502273e+16,4.764328e+19,9.071281e+22,1.727172e+26,3.288535e+29,6.261371e+32,1.192165e+36,2.269882e+39,4.321856e+42,8.228813e+45,1.566766e+49,365000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19391,2480.0,6150400.0,1.525299e+10,3.782742e+13,9.381200e+16,2.326538e+20,5.769813e+23,1.430914e+27,3.548666e+30,8.800692e+33,2.182572e+37,5.412777e+40,1.342369e+44,3.329075e+47,8.256105e+50,325000.0
19392,1670.0,2788900.0,4.657463e+09,7.777963e+12,1.298920e+16,2.169196e+19,3.622558e+22,6.049671e+25,1.010295e+29,1.687193e+32,2.817612e+35,4.705412e+38,7.858038e+41,1.312292e+45,2.191528e+48,545000.0
19393,2403.0,5774409.0,1.387590e+10,3.334380e+13,8.012515e+16,1.925407e+20,4.626754e+23,1.111809e+27,2.671677e+30,6.420040e+33,1.542736e+37,3.707193e+40,8.908386e+43,2.140685e+47,5.144066e+50,519900.0
19394,3780.0,14288400.0,5.401015e+10,2.041584e+14,7.717187e+17,2.917097e+21,1.102662e+25,4.168064e+28,1.575528e+32,5.955497e+35,2.251178e+39,8.509452e+42,3.216573e+46,1.215865e+50,4.595968e+53,1153000.0
19395,2400.0,5760000.0,1.382400e+10,3.317760e+13,7.962624e+16,1.911030e+20,4.586471e+23,1.100753e+27,2.641808e+30,6.340338e+33,1.521681e+37,3.652035e+40,8.764883e+43,2.103572e+47,5.048573e+50,338000.0