In [5]:
import pandas as pd
import numpy as np
df=pd.read_csv("song_data.csv")
df

,user_id,song_id,listen_count,title,artist,song
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Jack Johnson,The Cove - Jack Johnson
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,Entre Dos Aguas,Paco De Lucia,Entre Dos Aguas - Paco De Lucia
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Kanye West,Stronger - Kanye West
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,Jack Johnson,Constellations - Jack Johnson
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,Foo Fighters,Learn To Fly - Foo Fighters
...,...,...,...,...,...,...
1116604,276e43ad698705e5011e5091f367d951b21246f5,SOWTYVO12AB0180BDA,8,Surf Wax America,Weezer,Surf Wax America - Weezer
1116605,276e43ad698705e5011e5091f367d951b21246f5,SOWZHOY12A6701F9FC,1,Kill The King,Megadeth,Kill The King - Megadeth
1116606,276e43ad698705e5011e5091f367d951b21246f5,SOXJOZW12A6701E90E,7,You Think I Ain\'t Worth A Dollar_ But I Feel ...,Queens Of The Stone Age,You Think I Ain\'t Worth A Dollar_ But I Feel ...
1116607,276e43ad698705e5011e5091f367d951b21246f5,SOXNKNC12A6701F7A8,1,Superbeast,Rob Zombie,Superbeast - Rob Zombie
1116608,276e43ad698705e5011e5091f367d951b21246f5,SOYRMVO12A6701D106,1,Keep Away,Godsmack,Keep Away - Godsmack

In [48]:
duplicate=df
duplicate["listen_count"]=1
duplicate

,user_id,song_id,listen_count,title,artist,song
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Jack Johnson,The Cove - Jack Johnson
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,1,Entre Dos Aguas,Paco De Lucia,Entre Dos Aguas - Paco De Lucia
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Kanye West,Stronger - Kanye West
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,Jack Johnson,Constellations - Jack Johnson
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,Foo Fighters,Learn To Fly - Foo Fighters
...,...,...,...,...,...,...
1116604,276e43ad698705e5011e5091f367d951b21246f5,SOWTYVO12AB0180BDA,1,Surf Wax America,Weezer,Surf Wax America - Weezer
1116605,276e43ad698705e5011e5091f367d951b21246f5,SOWZHOY12A6701F9FC,1,Kill The King,Megadeth,Kill The King - Megadeth
1116606,276e43ad698705e5011e5091f367d951b21246f5,SOXJOZW12A6701E90E,1,You Think I Ain\'t Worth A Dollar_ But I Feel ...,Queens Of The Stone Age,You Think I Ain\'t Worth A Dollar_ But I Feel ...
1116607,276e43ad698705e5011e5091f367d951b21246f5,SOXNKNC12A6701F7A8,1,Superbeast,Rob Zombie,Superbeast - Rob Zombie
1116608,276e43ad698705e5011e5091f367d951b21246f5,SOYRMVO12A6701D106,1,Keep Away,Godsmack,Keep Away - Godsmack

In [49]:
df1=duplicate.groupby("artist").sum()
df1

                      listen_count
artist
!!!                             53
+ / - {Plus/Minus}             184
+44                            124
10 Years                       128
1001                            43
...                            ...
moe.                            81
rinÃ´Ã§Ã©rÃ´se                      45
the bird and the bee          1520
themselves                      44
tobyMac                        149

[3375 rows x 1 columns]

In [50]:
df1.index[df1["listen_count"]==df1["listen_count"].max()]

Index(['Coldplay'], dtype='object', name='artist')

In [51]:
df1.loc["Kanye West"]

listen_count    3775
Name: Kanye West, dtype: int64

In [52]:
df1.loc["Foo Fighters"]

listen_count    3429
Name: Foo Fighters, dtype: int64

In [53]:
df1.loc["Taylor Swift"]

listen_count    6227
Name: Taylor Swift, dtype: int64

In [54]:
df1.loc["Lady GaGa"]

listen_count    4129
Name: Lady GaGa, dtype: int64

In [55]:
df2=df.groupby("artist").sum()

In [56]:
df2.index[df2["listen_count"]==df2["listen_count"].max()]

Index(['Coldplay'], dtype='object', name='artist')

In [57]:
df2.index[df2["listen_count"]==df2["listen_count"].min()]

Index(['William Tabbert'], dtype='object', name='artist')

In [58]:
df1.sort_values("listen_count")

                        listen_count
artist
William Tabbert                   12
Elvis Perkins                     20
Reel Feelings                     22
harvey summers                    22
Giannis Aggelakas                 23
...                              ...
The Black Keys                  8141
Justin Bieber                   8796
Kings Of Leon                   9908
Florence + The Machine         10082
Coldplay                       13945

[3375 rows x 1 columns]

In [59]:
df2.sort_values("listen_count")

                        listen_count
artist
William Tabbert                   12
Elvis Perkins                     20
Reel Feelings                     22
harvey summers                    22
Giannis Aggelakas                 23
...                              ...
The Black Keys                  8141
Justin Bieber                   8796
Kings Of Leon                   9908
Florence + The Machine         10082
Coldplay                       13945

[3375 rows x 1 columns]